pipeline {
    agent any

    environment {
        // Thay 'tuanit' bằng Username Docker Hub của mày
        DOCKER_HUB_USER = 'tuanotuan' 
        IMAGE_NAME = 'backend-library'
        // Gọi đúng cái ID mày vừa tạo ở bước trước
        DOCKER_HUB_CREDS = credentials('docker-hub-creds')
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                echo 'Đang chạy JUnit 5... (Giả lập pass 100%)'
                // Sau này mày cài Maven/Gradle thì chạy lệnh test thật ở đây
                sh 'echo "Tests passed!"'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    // Đăng nhập Docker Hub dùng Credentials đã lưu
                    sh "echo $DOCKER_HUB_CREDS_PSW | docker login -u $DOCKER_HUB_CREDS_USR --password-stdin"
                    
                    // Build image
                    sh "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest ."
                    
                    // Push lên Docker Hub
                    sh "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest"
                }
            }
        }
    }

    post {
        success {
            echo 'Ngon rồi Tuấn ơi! Backend đã lên Docker Hub an toàn.'
        }
        failure {
            echo 'Toang rồi! Check lại log đi mày.'
        }
    }
}