pipeline {
    agent any

    // Chỉ 1 block tools
    tools {
        dockerTool 'my-docker'
    }

    // Chỉ 1 block environment DUY NHẤT chứa tất cả biến
    environment {
        DOCKER_HUB_USER = 'tuanotuan' 
        IMAGE_NAME = 'backend-library'
        DOCKER_HUB_CREDS = credentials('docker-hub-creds')
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                echo 'Đang chạy JUnit 5... (Giả lập pass 100%)'
                sh 'echo "Tests passed!"'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    // Dùng dấu nháy đơn '' để tránh lỗi bảo mật nội suy chuỗi (interpolation)
                    sh 'echo $DOCKER_HUB_CREDS_PSW | docker login -u $DOCKER_HUB_CREDS_USR --password-stdin'
                    
                    // Build image
                    sh "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest -f backend/Dockerfile backend"
                    
                    // Push lên Docker Hub
                    sh "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest"
                }
            }
            
        }
        stage('Deploy to Web Server') {
            steps {
                // Gọi cái chìa khóa vạn năng mày tạo lúc nãy
                sshagent(['web-server-creds']) {
                    // Thay IP_SERVER_WEB bằng IP con EC2 cũ (con chạy Nginx)
                    sh "ssh -o StrictHostKeyChecking=no ubuntu@52.77.117.33 'cd ~/library-management-devops && docker compose pull backend && docker compose up -d backend'"
                }
            }
        }
    }

    post {
        success {
            echo 'Ngon rồi Tuấn ơi! Backend đã lên Docker Hub an toàn.'
        }
        failure {
            echo 'Toang rồi! Check lại log đi mày.'
        }
    }
}